name: build RevEng60 and push to nuget

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 建立dotnet环境
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.101
    #- name: Build
    #  run: dotnet build ./src/GUI/RevEng.Core.60/RevEng.Core.60.csproj --configuration Release      
    - name: Install Nuget
      uses: nuget/setup-nuget@v1
      with:        
        nuget-version: '5.x'
    - name: Push To Nuget
      run: |
        nuget pack ./src/GUI/RevEng.Core.60/RevEng.Core.60.csproj -IncludeReferencedProjects -Version 2022.2.14
        #nuget push ./bin/Release/*.nupkg -Source https://api.nuget.org/v3/index.json -SkipDuplicate -ApiKey ${{ secrets.NugetKey }} -NoSymbol
        # nuget push ./bin/Release/*.nupkg -Source github -SkipDuplicate
