name: dotnet6 build and push to nuget

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 建立dotnet环境
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.101
    - name: 安装依赖
      run: dotnet restore
    - name: 构建
      run: dotnet build --configuration Release --no-restore    
    - name: 安装nuget 
      uses: nuget/setup-nuget@v1
      with:        
        nuget-version: '5.x'
    - name: 发布生成包到github和nuget
      run: |
        nuget push ./bin/Release/*.nupkg -Source https://api.nuget.org/v3/index.json -SkipDuplicate -ApiKey ${{ secrets.NugetKey }} -NoSymbol
        # nuget push ./bin/Release/*.nupkg -Source github -SkipDuplicate
